<?php die( 'These aren\'t the droids you\'re looking for...' );

/**
 * Extract of translatable text strings from the lib/pro classes.
 */
_x( 'days', 'option comment', 'wpsso-schema-json-ld' );
_x( 'hours', 'option comment', 'wpsso-schema-json-ld' );
_x( 'mins', 'option comment', 'wpsso-schema-json-ld' );
_x( 'secs', 'option comment', 'wpsso-schema-json-ld' );
__( 'Save a draft version or publish the %s to update this value.', 'wpsso-schema-json-ld' );
_x( 'Schema Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'Name / Title', 'option label', 'wpsso-schema-json-ld' );
_x( 'Alternate Name', 'option label', 'wpsso-schema-json-ld' );
// translators: Please ignore - translation uses a different text domain.
_x( 'Description', 'option label', 'wpsso' );
_x( 'Microdata Type URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Same-As URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Creative Work Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Headline', 'option label', 'wpsso-schema-json-ld' );
_x( 'Full Text', 'option label', 'wpsso-schema-json-ld' );
_x( 'Keywords', 'option label', 'wpsso-schema-json-ld' );
_x( 'Language', 'option label', 'wpsso-schema-json-ld' );
_x( 'Family Friendly', 'option label', 'wpsso-schema-json-ld' );
_x( 'Copyright Year', 'option label', 'wpsso-schema-json-ld' );
_x( 'Publisher', 'option label', 'wpsso-schema-json-ld' );
_x( 'Service Provider', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Event Language', 'option label', 'wpsso-schema-json-ld' );
_x( 'Organizer Org', 'option label', 'wpsso-schema-json-ld' );
_x( 'Organizer Person', 'option label', 'wpsso-schema-json-ld' );
_x( 'Performer Org', 'option label', 'wpsso-schema-json-ld' );
_x( 'Performer Person', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Venue', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Start', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event End', 'option label', 'wpsso-schema-json-ld' );
_x( 'Offers Start', 'option label', 'wpsso-schema-json-ld' );
_x( 'Offers End', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offers', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Price', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Currency', 'option label', 'wpsso-schema-json-ld' );
_x( 'Event Offer Availability', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'How-To Makes', 'option label', 'wpsso-schema-json-ld' );
_x( 'Preparation Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Total Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Supplies', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Tools', 'option label', 'wpsso-schema-json-ld' );
_x( 'How-To Steps', 'option label', 'wpsso-schema-json-ld' );
_x( '%1$s Step or %2$s Section', 'option label', 'wpsso-schema-json-ld' );
_x( 'Section Name or Step Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Section Description or Direction Text', 'option label', 'wpsso-schema-json-ld' );
_x( 'Job Posting Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Job Title', 'option label', 'wpsso-schema-json-ld' );
_x( 'Hiring Organization', 'option label', 'wpsso-schema-json-ld' );
_x( 'Job Location', 'option label', 'wpsso-schema-json-ld' );
_x( 'Base Salary', 'option label', 'wpsso-schema-json-ld' );
_x( 'per', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Employment Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'Job Posting Expires', 'option label', 'wpsso-schema-json-ld' );
_x( 'Movie Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Cast Names', 'option label', 'wpsso-schema-json-ld' );
_x( 'Director Names', 'option label', 'wpsso-schema-json-ld' );
_x( 'Production Company', 'option label', 'wpsso-schema-json-ld' );
_x( 'Movie Runtime', 'option label', 'wpsso-schema-json-ld' );
_x( 'Organization Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Organization', 'option label', 'wpsso-schema-json-ld' );
_x( 'Person Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Person', 'option label', 'wpsso-schema-json-ld' );
_x( 'QA Page Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'QA Heading', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Recipe Cuisine', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Course', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Makes', 'option label', 'wpsso-schema-json-ld' );
_x( 'Cooking Method', 'option label', 'wpsso-schema-json-ld' );
_x( 'Preparation Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Cooking Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Total Time', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Ingredients', 'option label', 'wpsso-schema-json-ld' );
_x( 'Recipe Instructions', 'option label', 'wpsso-schema-json-ld' );
_x( 'Nutrition Information per Serving', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Serving Size', 'option label', 'wpsso-schema-json-ld' );
_x( 'Calories', 'option label', 'wpsso-schema-json-ld' );
_x( 'calories', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Protein', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of protein', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Fiber', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of fiber', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Carbohydrates', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of carbohydrates', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Sugar', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of sugar', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Sodium', 'option label', 'wpsso-schema-json-ld' );
_x( 'milligrams of sodium', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Saturated Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of saturated fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Unsaturated Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of unsaturated fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Trans Fat', 'option label', 'wpsso-schema-json-ld' );
_x( 'grams of trans fat', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Cholesterol', 'option label', 'wpsso-schema-json-ld' );
_x( 'milligrams of cholesterol', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Review Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Review Rating', 'option label', 'wpsso-schema-json-ld' );
_x( 'from', 'option comment', 'wpsso-schema-json-ld' );
_x( 'to', 'option comment', 'wpsso-schema-json-ld' );
_x( 'Review Rating Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Review Subject URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Claim Review Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Claim Short Summary', 'option label', 'wpsso-schema-json-ld' );
_x( 'Claim Made on Date', 'option label', 'wpsso-schema-json-ld' );
_x( 'Claim Author Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'Claim Author Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Claim Author URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'First Appearance URL', 'option label', 'wpsso-schema-json-ld' );
_x( 'Software Application Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Operating System', 'option label', 'wpsso-schema-json-ld' );
_x( 'Schema Type', 'option label', 'wpsso-schema-json-ld' );
_x( 'Name / Title', 'option label', 'wpsso-schema-json-ld' );
_x( 'Alternate Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Microdata Type URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Same-As URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Name / Title', 'option label', 'wpsso-schema-json-ld' );
_x( 'Alternate Name', 'option label', 'wpsso-schema-json-ld' );
_x( 'Other Profile Page URLs', 'option label', 'wpsso-schema-json-ld' );
_x( 'Person Information', 'metabox title', 'wpsso-schema-json-ld' );
_x( 'Job Title', 'option label', 'wpsso-schema-json-ld' );
